/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Kantrus
 * Kantrus Server
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationError } from "./validationError";

export interface HTTPValidationError {
  detail?: ValidationError[];
}
