/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Kantrus
 * Kantrus Server
 * OpenAPI spec version: 1.0.0
 */

export interface ValidationError {
  loc: string[];
  msg: string;
  type: string;
}
